from pathlib import Path

p=Path('windows-installer/src/video-library.html')
s=p.read_text(encoding='utf-8')

css=r'''

    /* CINEMA_LIBRARY_RESPONSIVE_IMAGE_SHELL_V1 */
    :root{--nav-w:214px;--header-h:104px;--mobile-nav-h:62px}
    .app{max-width:1600px;display:grid;grid-template-columns:var(--nav-w) minmax(0,1fr);grid-template-rows:auto auto auto;column-gap:18px;padding:14px 16px 76px}
    header{grid-column:1/-1;min-height:var(--header-h);overflow:hidden;background-image:
      linear-gradient(90deg,rgba(17,10,8,.28),rgba(17,10,8,.08),rgba(17,10,8,.28)),
      url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 1600 180'%3E%3Cdefs%3E%3ClinearGradient id='c' x1='0' y1='0' x2='0' y2='1'%3E%3Cstop stop-color='%2376171e'/%3E%3Cstop offset='1' stop-color='%23310c10'/%3E%3C/linearGradient%3E%3ClinearGradient id='w' x1='0' y1='0' x2='1' y2='0'%3E%3Cstop stop-color='%23331e13'/%3E%3Cstop offset='.5' stop-color='%2370522f'/%3E%3Cstop offset='1' stop-color='%2323140e'/%3E%3C/linearGradient%3E%3CradialGradient id='l'%3E%3Cstop stop-color='%23ffe8a9' stop-opacity='.95'/%3E%3Cstop offset='.32' stop-color='%23d69b42' stop-opacity='.45'/%3E%3Cstop offset='1' stop-color='%23000' stop-opacity='0'/%3E%3C/radialGradient%3E%3C/defs%3E%3Crect width='1600' height='180' fill='%23100b09'/%3E%3Crect y='8' width='1600' height='125' fill='url(%23c)'/%3E%3Cg opacity='.22' stroke='%23f2bd69'%3E%3Cpath d='M0 15 Q100 110 200 15 T400 15 T600 15 T800 15 T1000 15 T1200 15 T1400 15 T1600 15' fill='none' stroke-width='5'/%3E%3Cpath d='M0 28 Q100 132 200 28 T400 28 T600 28 T800 28 T1000 28 T1200 28 T1400 28 T1600 28' fill='none' stroke-width='2'/%3E%3C/g%3E%3Crect y='132' width='1600' height='34' fill='url(%23w)'/%3E%3Crect y='135' width='1600' height='2' fill='%23c7984d' opacity='.8'/%3E%3Ccircle cx='175' cy='72' r='92' fill='url(%23l)'/%3E%3Ccircle cx='1425' cy='72' r='92' fill='url(%23l)'/%3E%3Cg fill='%23d5a555'%3E%3Crect x='166' y='15' width='18' height='42' rx='4'/%3E%3Crect x='1416' y='15' width='18' height='42' rx='4'/%3E%3C/g%3E%3C/svg%3E");
      background-size:cover;background-position:center;box-shadow:0 12px 34px rgba(0,0,0,.46),inset 0 -1px #a2763d}
    header::before,header::after{display:none}
    .brand{position:relative;z-index:2;padding:4px 18px 5px;background:linear-gradient(90deg,rgba(10,7,5,.78),rgba(10,7,5,.36),transparent);border-left:1px solid rgba(213,165,85,.42)}
    .brand h1{font-size:35px;text-shadow:0 2px 4px #000,0 0 16px rgba(241,217,154,.12)}
    .header-actions{position:relative;z-index:2;margin-left:auto;padding:10px 0 10px 22px;background:linear-gradient(90deg,transparent,rgba(12,9,7,.64));backdrop-filter:blur(2px)}
    .cinema-menu-toggle{display:none;position:relative;z-index:4;width:44px;height:44px;border:1px solid #9c7440;background:rgba(15,11,8,.88);color:#f0d69e;border-radius:3px;font-size:22px;cursor:pointer}
    .cinema-nav{grid-column:1;grid-row:2;position:sticky;top:14px;align-self:start;min-height:690px;border:1px solid #62492f;border-radius:5px;overflow:hidden;background-image:
      linear-gradient(180deg,rgba(14,11,9,.10),rgba(14,11,9,.78)),
      url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 320 980'%3E%3Cdefs%3E%3ClinearGradient id='b' x1='0' y1='0' x2='0' y2='1'%3E%3Cstop stop-color='%23181310'/%3E%3Cstop offset='.65' stop-color='%23110e0c'/%3E%3Cstop offset='1' stop-color='%23201510'/%3E%3C/linearGradient%3E%3ClinearGradient id='g' x1='0' y1='0' x2='0' y2='1'%3E%3Cstop stop-color='%23d29a43'/%3E%3Cstop offset='1' stop-color='%23673c1c'/%3E%3C/linearGradient%3E%3C/defs%3E%3Crect width='320' height='980' fill='url(%23b)'/%3E%3Cg opacity='.12' stroke='%23b98a48'%3E%3Cpath d='M0 90H320M0 180H320M0 270H320M0 360H320M0 450H320M0 540H320'/%3E%3Cpath d='M40 0V600M120 0V600M200 0V600M280 0V600'/%3E%3C/g%3E%3Cg transform='translate(22 655)'%3E%3Crect x='20' y='85' width='236' height='175' fill='%23191410' stroke='%238a6131' stroke-width='3'/%3E%3Cpath d='M4 85L138 12L274 85Z' fill='%23271a11' stroke='%238a6131' stroke-width='3'/%3E%3Crect x='82' y='132' width='116' height='128' fill='%230a0807' stroke='%23b07b38'/%3E%3Crect x='49' y='110' width='48' height='55' fill='%23d89c42' opacity='.28'/%3E%3Crect x='203' y='110' width='48' height='55' fill='%23d89c42' opacity='.28'/%3E%3Crect x='96' y='58' width='84' height='50' fill='url(%23g)' stroke='%23e0b968'/%3E%3Ccircle cx='138' cy='202' r='60' fill='%23d89c42' opacity='.08'/%3E%3C/g%3E%3C/svg%3E");background-size:cover;background-position:center;box-shadow:0 12px 30px rgba(0,0,0,.36),inset 0 0 0 4px rgba(8,6,5,.42)}
    .cinema-nav-inner{padding:13px 10px 235px}
    .cinema-nav-title{padding:8px 9px 14px;border-bottom:1px solid #60472f;color:#e8cf9a;font:600 13px/1.3 "Yu Mincho","Hiragino Mincho ProN",serif;letter-spacing:.08em}
    .cinema-nav-title small{display:block;margin-top:4px;color:#80623e;font:700 6px/1 Georgia,serif;letter-spacing:.20em}
    .cinema-nav-list{display:grid;gap:7px;margin-top:11px}
    .cinema-nav-item{display:grid;grid-template-columns:32px minmax(0,1fr);align-items:center;gap:8px;width:100%;min-height:55px;padding:8px 9px;border:1px solid transparent;border-radius:3px;background:rgba(18,14,11,.70);color:#e6d6b8;text-align:left;cursor:pointer;font-family:"Yu Mincho","Hiragino Mincho ProN",serif}
    .cinema-nav-item:hover,.cinema-nav-item:focus-visible,.cinema-nav-item.active{border-color:#b48644;background:linear-gradient(180deg,rgba(119,35,38,.94),rgba(70,18,20,.95));color:#fff0cc;outline:none}
    .cinema-nav-icon{display:grid;place-items:center;color:#d8ad62;font-size:21px}
    .cinema-nav-label{font-size:14px;line-height:1.25}.cinema-nav-label small{display:block;margin-top:3px;color:#947c5a;font-size:8px;letter-spacing:.05em}
    .cinema-nav-item.active .cinema-nav-label small,.cinema-nav-item:hover .cinema-nav-label small{color:#d8bd8c}
    main{grid-column:2;grid-row:2;min-width:0}
    .tmdb-credit{grid-column:1/-1;grid-row:3;position:relative;min-height:68px;margin-top:24px;padding:20px 230px 14px;border:1px solid #64452d;border-radius:3px;background-image:
      linear-gradient(rgba(77,14,17,.74),rgba(49,10,12,.90)),
      url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 1600 120'%3E%3Cdefs%3E%3Cpattern id='p' width='24' height='24' patternUnits='userSpaceOnUse'%3E%3Cpath d='M0 12H24M12 0V24' stroke='%23d9a85c' stroke-opacity='.08'/%3E%3Ccircle cx='12' cy='12' r='2' fill='%23e7bd70' fill-opacity='.12'/%3E%3C/pattern%3E%3C/defs%3E%3Crect width='1600' height='120' fill='%2367181d'/%3E%3Crect width='1600' height='120' fill='url(%23p)'/%3E%3Cpath d='M0 8H1600M0 112H1600' stroke='%23d0a35b' stroke-width='2' opacity='.72'/%3E%3C/svg%3E");background-size:cover;color:#a99370;text-align:center;letter-spacing:.04em}
    .cinema-footer-motto{position:absolute;left:24px;top:22px;color:#d0aa67;font-family:"Yu Mincho","Hiragino Mincho ProN",serif;font-size:11px;letter-spacing:.14em}.cinema-footer-mark{position:absolute;right:24px;top:20px;color:#d1aa60;font:700 10px/1.7 Georgia,serif;letter-spacing:.32em}
    .cinema-mobile-nav{display:none}
    .cinema-drawer-backdrop{display:none}
    @media(max-width:1199px){
      .app{display:block;max-width:1180px;padding:10px 12px 72px}.cinema-menu-toggle{display:grid;place-items:center;flex:0 0 auto}header{min-height:86px;padding:12px 14px;gap:10px}.brand{padding-left:10px}.brand h1{font-size:29px}.header-actions{margin-left:auto}.header-actions>div{display:none}.cinema-nav{position:fixed;z-index:1202;left:0;top:0;bottom:0;width:min(290px,86vw);height:100dvh;min-height:0;border-radius:0;transform:translateX(-105%);transition:transform .20s ease;overflow:auto}.cinema-nav.open{transform:translateX(0)}.cinema-nav-inner{min-height:100%;padding-bottom:235px}.cinema-drawer-backdrop{position:fixed;z-index:1201;inset:0;background:rgba(0,0,0,.62);backdrop-filter:blur(2px)}.cinema-drawer-backdrop.open{display:block}main{min-width:0}.tmdb-credit{margin-top:20px;padding:18px 180px 13px}.cinema-footer-motto{left:18px}.cinema-footer-mark{right:18px}
    }
    @media(max-width:767px){
      :root{--mobile-nav-h:62px}.app{padding:7px 8px calc(var(--mobile-nav-h) + 22px)}header{min-height:70px;margin-bottom:12px;padding:8px 9px;background-position:center top}.cinema-menu-toggle{width:39px;height:39px;font-size:20px}.brand{padding:2px 7px;border-left:0}.brand-kicker{display:none}.brand h1{font-size:22px;white-space:nowrap}.brand p{margin-top:2px;font-size:8px;letter-spacing:.10em}.brand-mark{width:21px;height:21px}.header-actions{margin-left:auto;padding:0;border:0;background:none}.header-actions #scanButton{display:none}.home-strip{margin-bottom:16px;padding:11px 9px 9px}.catalog-heading{padding-left:3px;padding-right:3px}.catalog .grid{grid-template-columns:repeat(2,minmax(0,1fr))}.hero-layout{grid-template-columns:96px minmax(0,1fr);gap:15px}.hero-poster{width:96px}.hero-poster-fallback{width:96px;min-height:144px}.hero-body h2{font-size:25px}.overview,.credits{grid-column:1/-1}.tmdb-credit{min-height:50px;margin-bottom:4px;padding:14px 12px 10px;font-size:9px}.cinema-footer-motto,.cinema-footer-mark{display:none}.cinema-mobile-nav{position:fixed;z-index:1100;left:0;right:0;bottom:0;height:var(--mobile-nav-h);display:grid;grid-template-columns:repeat(4,1fr);padding-bottom:env(safe-area-inset-bottom);border-top:1px solid #9a6d37;background:linear-gradient(180deg,rgba(55,12,15,.97),rgba(22,10,9,.99));box-shadow:0 -8px 26px rgba(0,0,0,.48)}.cinema-mobile-nav button{border:0;border-right:1px solid rgba(190,143,72,.18);background:transparent;color:#d9bf8d;font-family:"Yu Mincho","Hiragino Mincho ProN",serif;font-size:9px;cursor:pointer}.cinema-mobile-nav button:focus-visible{outline:1px solid #d4aa5c;outline-offset:-3px}.cinema-mobile-nav span{display:block;margin-bottom:2px;color:#e0b35e;font-size:18px}.cinema-nav{width:min(310px,88vw)}
    }
    @media(max-width:420px){.brand h1{font-size:19px}.brand p{display:none}.catalog .grid{gap:10px 7px}.catalog .card h2{font-size:12px}.hero-layout{grid-template-columns:82px minmax(0,1fr);gap:12px}.hero-poster{width:82px}.hero-poster-fallback{width:82px;min-height:123px}.hero-body h2{font-size:21px}.cinema-mobile-nav button{font-size:8px}}
'''
if 'CINEMA_LIBRARY_RESPONSIVE_IMAGE_SHELL_V1' not in s:
    s=s.replace('\n  </style>','\n'+css+'\n  </style>')

old='''<div class="app">\n  <header>\n    <div class="brand"><div class="brand-kicker">PRIVATE CINEMA ARCHIVE</div><h1><span class="brand-mark" aria-hidden="true">◉</span> シネマ蔵書館</h1><p>映画で、また会える。</p></div>\n    <div class="header-actions"><div><div class="user" id="currentUser"></div><div class="stats" id="stats">読み込み中...</div><div class="scan-status" id="scanStatus"></div></div><button class="ghost" id="scanButton">再スキャン</button></div>\n  </header>\n  <main>'''
new='''<div class="app">\n  <header>\n    <button class="cinema-menu-toggle" id="cinemaMenuToggle" type="button" aria-label="メニューを開く" aria-controls="cinemaNav" aria-expanded="false">☰</button>\n    <div class="brand"><div class="brand-kicker">PRIVATE CINEMA ARCHIVE</div><h1><span class="brand-mark" aria-hidden="true">◉</span> シネマ蔵書館</h1><p>映画で、また会える。</p></div>\n    <div class="header-actions"><div><div class="user" id="currentUser"></div><div class="stats" id="stats">読み込み中...</div><div class="scan-status" id="scanStatus"></div></div><button class="ghost" id="scanButton">再スキャン</button></div>\n  </header>\n  <aside class="cinema-nav" id="cinemaNav" aria-label="シネマ蔵書館メニュー"><div class="cinema-nav-inner"><div class="cinema-nav-title">館内案内<small>CINEMA DIRECTORY</small></div><nav class="cinema-nav-list">\n    <button class="cinema-nav-item active" type="button" data-cinema-nav="continue"><span class="cinema-nav-icon">●</span><span class="cinema-nav-label">上映中<small>いま観られる作品</small></span></button>\n    <button class="cinema-nav-item" type="button" data-cinema-nav="next"><span class="cinema-nav-icon">▣</span><span class="cinema-nav-label">次回上映<small>次に観る一本</small></span></button>\n    <button class="cinema-nav-item" type="button" data-cinema-nav="catalog"><span class="cinema-nav-icon">▤</span><span class="cinema-nav-label">作品目録<small>すべての作品</small></span></button>\n    <button class="cinema-nav-item" type="button" data-cinema-nav="people"><span class="cinema-nav-icon">●●</span><span class="cinema-nav-label">俳優・監督検索<small>人物名から探す</small></span></button>\n    <button class="cinema-nav-item" type="button" data-cinema-nav="diagnostics"><span class="cinema-nav-icon">☆</span><span class="cinema-nav-label">診断の部屋<small>ライブラリ状態</small></span></button>\n    <button class="cinema-nav-item" type="button" data-cinema-nav="scan"><span class="cinema-nav-icon">↻</span><span class="cinema-nav-label">再スキャン<small>蔵書を再確認</small></span></button>\n  </nav></div></aside>\n  <div class="cinema-drawer-backdrop" id="cinemaDrawerBackdrop" aria-hidden="true"></div>\n  <main>'''
if old not in s: raise SystemExit('header anchor not found')
s=s.replace(old,new)

old_footer='''  <footer class="tmdb-credit">This product uses the TMDB API but is not endorsed or certified by TMDB. · <a href="https://www.themoviedb.org" target="_blank" rel="noopener noreferrer">TMDB</a></footer>\n</div>'''
new_footer='''  <footer class="tmdb-credit"><span class="cinema-footer-motto">映画は、人生のよき友だ。</span><span class="cinema-footer-mark">CINEMA ◉ ARCHIVE</span>This product uses the TMDB API but is not endorsed or certified by TMDB. · <a href="https://www.themoviedb.org" target="_blank" rel="noopener noreferrer">TMDB</a></footer>\n</div>\n<nav class="cinema-mobile-nav" aria-label="モバイルナビ"><button type="button" data-cinema-nav="continue"><span>●</span>上映中</button><button type="button" data-cinema-nav="next"><span>▣</span>次回上映</button><button type="button" data-cinema-nav="catalog"><span>▤</span>作品目録</button><button type="button" data-cinema-nav="menu"><span>☰</span>メニュー</button></nav>'''
if old_footer not in s: raise SystemExit('footer anchor not found')
s=s.replace(old_footer,new_footer)

js=r'''
function setCinemaDrawer(open){const nav=$('cinemaNav'),back=$('cinemaDrawerBackdrop'),toggle=$('cinemaMenuToggle');if(!nav||!back||!toggle)return;nav.classList.toggle('open',!!open);back.classList.toggle('open',!!open);toggle.setAttribute('aria-expanded',open?'true':'false');document.body.classList.toggle('cinema-drawer-open',!!open)}
function cinemaScrollTo(id){if(location.hash&&!location.hash.startsWith('#/library'))location.hash='#/library';setTimeout(()=>{const el=$(id);if(el&&!el.hidden)el.scrollIntoView({behavior:'smooth',block:'start'})},80)}
function runCinemaNav(action){setCinemaDrawer(false);document.querySelectorAll('.cinema-nav-item').forEach(x=>x.classList.toggle('active',x.dataset.cinemaNav===action));if(action==='continue'){cinemaScrollTo('continueSection');return}if(action==='next'){cinemaScrollTo('nextSection');return}if(action==='catalog'){cinemaScrollTo('catalog');return}if(action==='people'){cinemaScrollTo('catalog');setTimeout(()=>{const q=$('search');if(q){q.focus();q.placeholder='俳優・監督名を入力...'}},120);return}if(action==='diagnostics'){location.href='/diagnostics.html';return}if(action==='scan'){runScan();return}if(action==='menu'){setCinemaDrawer(true)}}
function setupCinemaShell(){const toggle=$('cinemaMenuToggle'),back=$('cinemaDrawerBackdrop');if(toggle)toggle.onclick=()=>setCinemaDrawer(!($('cinemaNav')?.classList.contains('open')));if(back)back.onclick=()=>setCinemaDrawer(false);document.querySelectorAll('[data-cinema-nav]').forEach(b=>b.addEventListener('click',()=>runCinemaNav(b.dataset.cinemaNav||'')));window.addEventListener('resize',()=>{if(window.innerWidth>=1200)setCinemaDrawer(false)},{passive:true});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('cinemaNav')?.classList.contains('open'))setCinemaDrawer(false)})}
'''
anchor="function phaseLabel(p){return({PREPARING:'準備中'"
if js.strip() not in s:
    i=s.find(anchor)
    if i<0: raise SystemExit('js anchor not found')
    s=s[:i]+js+'\n'+s[i:]

old_init="(async()=>{await Promise.all([loadStats(),loadUser(),loadScan(),loadHome()]);route()})();"
new_init="(async()=>{setupCinemaShell();await Promise.all([loadStats(),loadUser(),loadScan(),loadHome()]);route()})();"
if old_init not in s: raise SystemExit('init anchor not found')
s=s.replace(old_init,new_init)
p.write_text(s,encoding='utf-8')

# documentation
Path('docs/58-1.1.0-responsive-image-cinema-shell.md').write_text('''# 1.1.0 シネマ蔵書館 画像装飾レスポンシブシェル\n\nIssue #130。Run #185 のデザインを、確認済みモックアップへさらに近づける。\n\n## 方針\n- 文字・操作要素はHTMLのまま保持する。\n- 赤い幕、木枠、真鍮、照明、映画館外観、フッター布地はSVG画像としてCSSへ埋め込む。\n- 追加の外部画像ファイルを必要としないため、PyInstaller/Installerの同梱漏れを防ぐ。\n\n## レスポンシブ\n- PC 1200px以上: 左サイドメニュー常設、フルヘッダー、装飾フッター。\n- Tablet 768-1199px: サイドメニューをドロワー化。ヘッダーを圧縮。\n- Smartphone 767px以下: 1カラム、ドロワー、下部4ボタンナビ、コンパクトヘッダー。\n\n## メニュー\n上映中、次回上映、作品目録、俳優・監督検索、診断、再スキャン。既存機能へ接続し、新規DB/APIは追加しない。\n\n## 非変更\n再生、TMDb、人物リンク、お気に入り、検索API、DBスキーマ、表示バージョン1.1.0。\n''',encoding='utf-8')

Path('tests/test_cinema_library_responsive_image_shell_v110.py').write_text('''from pathlib import Path\nimport unittest\n\nROOT=Path(__file__).resolve().parents[1]\nHTML=(ROOT/'windows-installer'/'src'/'video-library.html').read_text(encoding='utf-8')\n\nclass ResponsiveImageShellTests(unittest.TestCase):\n    def test_image_shell_marker_and_svg_images(self):\n        self.assertIn('CINEMA_LIBRARY_RESPONSIVE_IMAGE_SHELL_V1',HTML)\n        self.assertGreaterEqual(HTML.count('data:image/svg+xml'),3)\n    def test_desktop_sidebar_and_navigation(self):\n        self.assertIn('id="cinemaNav"',HTML)\n        self.assertIn('data-cinema-nav="continue"',HTML)\n        self.assertIn('data-cinema-nav="next"',HTML)\n        self.assertIn('data-cinema-nav="catalog"',HTML)\n        self.assertIn("location.href='/diagnostics.html'",HTML)\n    def test_tablet_and_phone_breakpoints(self):\n        self.assertIn('@media(max-width:1199px)',HTML)\n        self.assertIn('@media(max-width:767px)',HTML)\n        self.assertIn('cinema-mobile-nav',HTML)\n        self.assertIn('cinema-drawer-backdrop',HTML)\n    def test_drawer_accessibility_and_keyboard(self):\n        self.assertIn('aria-controls="cinemaNav"',HTML)\n        self.assertIn("toggle.setAttribute('aria-expanded'",HTML)\n        self.assertIn("e.key==='Escape'",HTML)\n    def test_existing_features_remain(self):\n        self.assertIn("const PAGE=60",HTML)\n        self.assertIn("FEATURE PRESENTATION",HTML)\n        self.assertIn("posterFallback",HTML)\n        self.assertIn("creditRow",HTML)\n        self.assertIn("runScan",HTML)\n        self.assertIn("/api/me/works/${w.id}/favorite",HTML)\n\nif __name__=='__main__':unittest.main()\n''',encoding='utf-8')
