from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
html_path = ROOT / 'windows-installer' / 'src' / 'video-library.html'
server_path = ROOT / 'windows-installer' / 'src' / 'server.py'
service_path = ROOT / 'windows-installer' / 'src' / 'library_service.py'


def replace_once(text: str, old: str, new: str, label: str) -> str:
    if old not in text:
        raise SystemExit(f'missing patch target: {label}')
    return text.replace(old, new, 1)

# library_service.py
text = service_path.read_text(encoding='utf-8')
text = replace_once(text, 'import sqlite3\nfrom typing import Any', 'import re\nimport sqlite3\nfrom typing import Any', 'library imports')
marker = '\n\ndef get_work(connection: sqlite3.Connection, work_id: int, *, user_id: int | None = None) -> dict[str, Any] | None:\n'
people_code = '''\n\n_PERSON_SPLIT_RE = re.compile(r"\\s*(?:、|,|，|;|；|\\||\\r?\\n|\\s+/\\s+)\\s*")\n\ndef list_people(connection: sqlite3.Connection, *, role: str) -> dict[str, Any]:\n    key = str(role or '').strip().casefold()\n    role_map = {\n        'director': ('director', 'director_or_direction'),\n        'directors': ('director', 'director_or_direction'),\n        'cast': ('cast', 'main_cast_or_voice_actors'),\n    }\n    if key not in role_map:\n        raise ValueError('role must be director or cast')\n    normalized_role, column = role_map[key]\n    rows = connection.execute(\n        f"SELECT id,{column} credits FROM works WHERE TRIM(COALESCE({column},''))<>''"\n    ).fetchall()\n    counts: dict[str, int] = {}\n    for row in rows:\n        seen: set[str] = set()\n        for raw in _PERSON_SPLIT_RE.split(str(row['credits'] or '')):\n            name = re.sub(r"\\s*(?:ほか|他)$", '', raw.strip()).strip()\n            if not name or name in seen:\n                continue\n            seen.add(name)\n            counts[name] = counts.get(name, 0) + 1\n    items = [\n        {'name': name, 'workCount': count}\n        for name, count in sorted(counts.items(), key=lambda item: (-item[1], item[0].casefold()))\n    ]\n    return {'role': normalized_role, 'total': len(items), 'items': items}\n'''
text = replace_once(text, marker, people_code + marker, 'list_people insertion')
service_path.write_text(text, encoding='utf-8')

# server.py
text = server_path.read_text(encoding='utf-8')
text = replace_once(text, 'from library_service import get_video, get_work, library_stats, list_work_videos, list_works', 'from library_service import get_video, get_work, library_stats, list_people, list_work_videos, list_works', 'server import')
old_diag = '''            if "diagnostics.html" not in text:\n                text = text.replace(\n                    '<button class="ghost" id="scanButton">再スキャン</button>',\n                    '<a class="ghost" style="text-decoration:none" href="/diagnostics.html">診断</a><button class="ghost" id="scanButton">再スキャン</button>',\n                )\n'''
text = replace_once(text, old_diag, '', 'remove diagnostic auto injection')
old_works = '''                    if path == "/api/works":\n                        self._json(200, list_works(connection, user_id=user_id, q=_first(query, "q"), category=_first(query, "category"),\n                                                   sort=_first(query, "sort") or "title", limit=_first(query, "limit"), offset=_first(query, "offset"))); return\n'''
new_works = '''                    if path == "/api/people":\n                        try:\n                            self._json(200, list_people(connection, role=_first(query, "role") or ""))\n                        except ValueError as exc:\n                            self._error(400, "INVALID_PEOPLE_ROLE", str(exc))\n                        return\n                    if path == "/api/works":\n                        self._json(200, list_works(connection, user_id=user_id, q=_first(query, "q"), category=_first(query, "category"),\n                                                   sort=_first(query, "sort") or "title", limit=_first(query, "limit"), offset=_first(query, "offset"))); return\n'''
text = replace_once(text, old_works, new_works, 'people api route')
server_path.write_text(text, encoding='utf-8')

# video-library.html
text = html_path.read_text(encoding='utf-8')
old_nav = '''    <button class="cinema-nav-item" type="button" data-scroll-target="continueSection"><span class="cinema-nav-icon">●</span><span>上映中<small>いま観られる作品</small></span></button>\n    <button class="cinema-nav-item" type="button" data-scroll-target="nextSection"><span class="cinema-nav-icon">◆</span><span>次回上映<small>次に観る作品</small></span></button>\n    <button class="cinema-nav-item" type="button" data-scroll-target="catalog"><span class="cinema-nav-icon">▣</span><span>作品目録<small>すべての作品</small></span></button>\n    <a class="cinema-nav-item" href="/diagnostics.html" style="text-decoration:none"><span class="cinema-nav-icon">◎</span><span>診断<small>ライブラリ状態</small></span></a>\n    <button class="cinema-nav-item" type="button" id="navScan"><span class="cinema-nav-icon">↻</span><span>再スキャン<small>蔵書を更新</small></span></button>\n'''
new_nav = '''    <button class="cinema-nav-item" type="button" data-route="#/home/continue"><span class="cinema-nav-icon">●</span><span>上映中<small>いま観られる作品</small></span></button>\n    <button class="cinema-nav-item" type="button" data-route="#/home/next"><span class="cinema-nav-icon">◆</span><span>次回上映<small>次に観る作品</small></span></button>\n    <button class="cinema-nav-item" type="button" data-route="#/library"><span class="cinema-nav-icon">▣</span><span>作品目録<small>すべての作品</small></span></button>\n    <button class="cinema-nav-item" type="button" data-route="#/people/directors"><span class="cinema-nav-icon">▤</span><span>監督／演出<small>監督・演出家から探す</small></span></button>\n    <button class="cinema-nav-item" type="button" data-route="#/people/cast"><span class="cinema-nav-icon">◎</span><span>主な出演者／声優<small>出演者・声優から探す</small></span></button>\n'''
text = replace_once(text, old_nav, new_nav, 'sidebar menu')
old_sections = '''    <section class="detail" id="detail" hidden><button class="ghost" id="back">← 作品目録</button><div id="workDetail"></div></section>\n'''
new_sections = '''    <section class="people-directory" id="peopleDirectory" hidden>\n      <div class="catalog-heading people-heading"><div class="catalog-title-block"><div class="catalog-kicker" id="peopleDirectoryKicker">PEOPLE DIRECTORY</div><h2 id="peopleDirectoryTitle">人物名鑑</h2><p id="peopleDirectoryDescription">人物から登録作品を探します。</p></div><div class="catalog-count"><strong id="peopleDirectoryCount">— 人</strong><small>REGISTERED PEOPLE</small></div></div>\n      <div class="people-grid" id="peopleDirectoryList"></div>\n    </section>\n    <section class="detail" id="detail" hidden><button class="ghost" id="back">← 作品目録</button><div id="workDetail"></div></section>\n'''
text = replace_once(text, old_sections, new_sections, 'people directory section')
css = '''\n    /* NAVIGATION_PEOPLE_MENU_V1 */\n    .people-directory[hidden]{display:none}.people-directory{padding:2px 0 28px}.people-heading{margin-bottom:16px}.people-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(190px,1fr));gap:10px}.people-card{min-height:76px;text-align:left;border:1px solid #72552d;border-radius:5px;background:linear-gradient(180deg,rgba(45,31,22,.94),rgba(23,18,15,.96));color:var(--cream);padding:13px 14px;cursor:pointer;box-shadow:inset 0 1px rgba(255,255,255,.04)}.people-card:hover,.people-card:focus-visible{border-color:var(--accent);outline:none;transform:translateY(-1px)}.people-card strong{display:block;font-family:"Yu Mincho","Hiragino Mincho ProN",serif;font-size:16px}.people-card small{display:block;margin-top:5px;color:var(--muted);font-size:11px}.cinema-nav-item.active{background:linear-gradient(90deg,rgba(126,28,28,.78),rgba(68,21,18,.55));border-color:#a36a32;color:#fff0c2}@media(max-width:767px){.people-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.people-card{min-height:68px;padding:11px}.people-card strong{font-size:14px}}@media(max-width:420px){.people-grid{grid-template-columns:1fr}}\n'''
text = replace_once(text, '\n</style>', css + '\n</style>', 'people css')
old_nav_js = '''document.querySelectorAll('[data-scroll-target]').forEach(b=>b.onclick=()=>{const target=$(b.dataset.scrollTarget);if(target&&!target.hidden)target.scrollIntoView({behavior:'smooth',block:'start'});else if(b.dataset.scrollTarget==='catalog'){location.hash='#/library';setTimeout(()=>$('catalog').scrollIntoView({behavior:'smooth'}),20)}setCinemaNav(false)});\n$('navScan').onclick=()=>{$('scanButton').click();setCinemaNav(false)};\n'''
new_nav_js = '''function updateCinemaNavActive(){const hash=location.hash||'#/library';document.querySelectorAll('.cinema-nav-item[data-route]').forEach(b=>b.classList.toggle('active',b.dataset.route===hash))}\ndocument.querySelectorAll('.cinema-nav-item[data-route]').forEach(b=>b.onclick=()=>{const next=b.dataset.route;if(location.hash===next)route();else location.hash=next;setCinemaNav(false)});\n'''
text = replace_once(text, old_nav_js, new_nav_js, 'nav route binding')
old_person = '''async function showPersonWorks(name){const person=String(name||'').trim();if(!person){location.hash='#/library';return}state.person=person;state.q=person;state.category='';$('search').value=person;$('detail').hidden=true;$('catalog').hidden=false;$('continueSection').hidden=true;$('nextSection').hidden=true;document.querySelectorAll('.chip').forEach(x=>x.classList.toggle('active',(x.dataset.category||'')===''));const msg=node('div','notice person-filter');msg.append('人物「',node('strong','',person),'」が関わる登録作品');$('message').replaceChildren(msg);await loadWorks(true)}\n'''
new_person = '''async function showPersonWorks(name){const person=String(name||'').trim();if(!person){location.hash='#/library';return}state.person=person;state.q=person;state.category='';$('search').value=person;$('detail').hidden=true;$('peopleDirectory').hidden=true;$('catalog').hidden=false;$('continueSection').hidden=true;$('nextSection').hidden=true;document.querySelectorAll('.chip').forEach(x=>x.classList.toggle('active',(x.dataset.category||'')===''));const msg=node('div','notice person-filter');msg.append('人物「',node('strong','',person),'」が関わる登録作品');$('message').replaceChildren(msg);updateCinemaNavActive();await loadWorks(true)}\nasync function showPeopleDirectory(role){const isDirector=role==='directors';state.person='';$('detail').hidden=true;$('catalog').hidden=true;$('continueSection').hidden=true;$('nextSection').hidden=true;$('peopleDirectory').hidden=false;$('peopleDirectoryKicker').textContent=isDirector?'DIRECTOR / DIRECTION DIRECTORY':'CAST / VOICE DIRECTORY';$('peopleDirectoryTitle').textContent=isDirector?'監督／演出':'主な出演者／声優';$('peopleDirectoryDescription').textContent=isDirector?'監督・演出家から、この蔵書館の作品を探します。':'出演者・声優から、この蔵書館の作品を探します。';const list=$('peopleDirectoryList');list.replaceChildren(node('div','notice','人物名鑑を読み込んでいます…'));try{const d=await api(`/api/people?role=${isDirector?'director':'cast'}`);$('peopleDirectoryCount').textContent=`${Number(d.total||0).toLocaleString()} 人`;list.replaceChildren();for(const p of d.items){const b=node('button','people-card');b.type='button';b.append(node('strong','',p.name),node('small','',`${p.workCount} 作品`));b.onclick=()=>{location.hash=`#/person/${encodeURIComponent(p.name)}`};list.append(b)}if(!d.items.length)list.append(node('div','empty','登録された人物情報がありません。'))}catch(e){list.replaceChildren(node('div','error',`人物名鑑を取得できませんでした。 ${e.message}`))}updateCinemaNavActive()}\n'''
text = replace_once(text, old_person, new_person, 'people directory js')
text = replace_once(text, "async function showWork(id){$('continueSection').hidden=true;$('nextSection').hidden=true;$('catalog').hidden=true;$('detail').hidden=false;", "async function showWork(id){$('continueSection').hidden=true;$('nextSection').hidden=true;$('catalog').hidden=true;$('peopleDirectory').hidden=true;$('detail').hidden=false;", 'hide people on detail')
old_route = '''function route(){const p=location.hash.match(/^#\\/person\\/(.+)$/);if(p){let name=p[1];try{name=decodeURIComponent(name)}catch{}showPersonWorks(name);return}const m=location.hash.match(/^#\\/work\\/(\\d+)$/);if(m){showWork(+m[1]);return}if(state.person){state.person='';state.q='';$('search').value=''}$('message').replaceChildren();$('detail').hidden=true;$('catalog').hidden=false;loadHome();if(!works.children.length)loadWorks(true)}\n'''
new_route = '''async function showLibraryRoute(target='catalog'){if(state.person){state.person='';state.q='';$('search').value='';$('headerSearch').value=''}$('message').replaceChildren();$('detail').hidden=true;$('peopleDirectory').hidden=true;$('catalog').hidden=false;await loadHome();if(!works.children.length)await loadWorks(true);updateCinemaNavActive();const id=target==='continue'?'continueSection':target==='next'?'nextSection':'catalog';const el=$(id);if(el&& !el.hidden)setTimeout(()=>el.scrollIntoView({behavior:'smooth',block:'start'}),30);else if(target!=='catalog')setTimeout(()=>$('catalog').scrollIntoView({behavior:'smooth',block:'start'}),30)}\nfunction route(){const people=location.hash.match(/^#\\/people\\/(directors|cast)$/);if(people){showPeopleDirectory(people[1]);return}const p=location.hash.match(/^#\\/person\\/(.+)$/);if(p){let name=p[1];try{name=decodeURIComponent(name)}catch{}showPersonWorks(name);return}const m=location.hash.match(/^#\\/work\\/(\\d+)$/);if(m){showWork(+m[1]);updateCinemaNavActive();return}if(location.hash==='#/home/continue'){showLibraryRoute('continue');return}if(location.hash==='#/home/next'){showLibraryRoute('next');return}showLibraryRoute('catalog')}\n'''
text = replace_once(text, old_route, new_route, 'route function')
html_path.write_text(text, encoding='utf-8')

print('navigation/people menu patch applied')
